package Marmoset;

import cs444.group9.AST.CodeGenerator.CodeCleaner;
import cs444.group9.JoosCompiler;
import org.junit.After;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import static org.assertj.core.api.Assertions.*;

import java.io.File;
import java.util.Arrays;
import java.util.Collection;

@RunWith(value = Parameterized.class)
public class A1Test {

    public JoosCompiler joosCompiler;

    private String _inputFile;
    private int _expectedReturnCode;

    // Inject via constructor
    public A1Test(String inputFile, int expectedReturnCode) {
        this._inputFile = inputFile;
        this._expectedReturnCode = expectedReturnCode;
        joosCompiler=new JoosCompiler();
    }

    // name attribute is optional, provide an unique name for test
    // multiple parameters, uses Collection<Object[]>
    @Parameterized.Parameters(name = "File: {0}")
    public static Collection<Object[]> data() {
        Object[][] A1Tests=new Object[][]{
                 /*{"/a1/J1_01.joos", 0},
                 {"/a1/J1_1_AmbiguousName_AccessResultFromMethod.joos",0},
                 {"/a1/J1_1_Cast_Complement.joos",0},
                 {"/a1/J1_1_Cast_MultipleCastOfSameValue_1.joos",0},
                 {"/a1/J1_1_Cast_MultipleCastOfSameValue_2.joos",0},
                 {"/a1/J1_1_Cast_MultipleCastOfSameValue_3.joos",0},
                 {"/a1/J1_1_Cast_MultipleReferenceArray.joos",0},
                 {"/a1/J1_1_Escapes_3DigitOctalAndDigit.joos",0},
                 {"/a1/J1_1_Instanceof_InLazyExp.joos",0},
                 {"/a1/J1_1_Instanceof_OfAdditiveExpression.joos",0},
                 {"/a1/J1_1_Instanceof_OfCastExpression.joos",0},
                 {"/a1/J1_1_IntRange_NegativeInt.joos",0},
                 {"/a1/J1_abstractclass.joos",0},
                 {"/a1/J1_abstractmethodwithoutbody.joos",0},
                 {"/a1/J1_arbitrarylocaldeclaration.joos",0},
                 {"/a1/J1_arithmeticoperations.joos",0},
                 {"/a1/J1_ArrayCreateAndIndex.joos",0},
                 {"/a1/J1_assignmentExp.joos",0},
                 {"/a1/J1_assignment.joos",0},
                 {"/a1/J1_barminusfoo.joos",0},
                 {"/a1/J1_BigInt.joos",0},
                 {"/a1/J1_charadd.joos",0},
                 {"/a1/J1_CharCast.joos",0},
                 {"/a1/J1_CharCharInit1.joos",0},
                 {"/a1/J1_CharCharInit2.joos",0},
                 {"/a1/J1_char_escape2.joos",0},
                 {"/a1/J1_char_escape3.joos",0},
                 {"/a1/J1_char_escape.joos",0},
                 {"/a1/J1_char.joos",0},
                 {"/a1/J1_charliterals.joos",0},
                 {"/a1/J1_classinstance.joos",0},
                 {"/a1/J1_commentsInExp1.joos",0},
                 {"/a1/J1_commentsInExp2.joos",0},
                 {"/a1/J1_commentsInExp3.joos",0},
                 {"/a1/J1_commentsInExp4.joos",0},
                 {"/a1/J1_commentsInExp5.joos",0},
                 {"/a1/J1_commentsInExp6.joos",0},
                 {"/a1/J1_commentsInExp7.joos",0},
                 {"/a1/J1_commentsInExp8.joos",0},
                 {"/a1/J1_commentsInExp9.joos",0},
                 {"/a1/J1_comparisonoperations.joos",0},
                 {"/a1/J1_concat_in_binop.joos",0},
                 {"/a1/J1_constructorbodycast.joos",0},
                 {"/a1/J1_constructorparameter.joos",0},
                 {"/a1/J1_constructorWithSameNameAsMethod.joos",0},
                 {"/a1/J1_eagerbooleanoperations.joos",0},
                 {"/a1/J1_EscapeEscape.joos",0},
                 {"/a1/J1_evalMethodInvocationFromParExp.joos",0},
                 {"/a1/J1_exp.joos",0},
           //      {"/a1/J1_extends.joos",0},
                 {"/a1/J1_externalcall.joos",0},
                 {"/a1/J1_finalclass2.joos",0},
                 {"/a1/J1_finalclass.joos",0},
                 {"/a1/J1_forAllwaysInit.joos",0},
                 {"/a1/J1_forAlwaysInitAsWhile.joos",0},
                 {"/a1/J1_forbodycast.joos",0},
                 {"/a1/J1_forifstatements1.joos",0},
                 {"/a1/J1_forifstatements2.joos",0},
                 {"/a1/J1_forifstatements3.joos",0},
                 {"/a1/J1_forinfor.joos",0},
                 {"/a1/J1_forinitcast.joos",0},
                 {"/a1/J1_forMethodInit.joos",0},
                 {"/a1/J1_forMethodUpdate2.joos",0},
                 {"/a1/J1_forMethodUpdate.joos",0},
                 {"/a1/J1_for_no_short_if.joos",0},
                 {"/a1/J1_forupdatecast.joos",0},
                 {"/a1/J1_ForUpdate_ClassCreation.joos",0},
                 {"/a1/J1_forWithoutExp.joos",0},
                 {"/a1/J1_forWithoutInit.joos",0},
                 {"/a1/J1_forWithoutUpdate.joos",0},
                 {"/a1/J1_hello_comment.joos",0},
                 {"/a1/J1_if.joos",0},
                 {"/a1/J1_ifThenElse.joos",0},
                 {"/a1/J1_if_then_for.joos",0},
                 {"/a1/J1_if_then.joos",0},
      //           {"/a1/J1_implements.joos",0},
                 {"/a1/J1_IntArrayDecl1.joos",0},
                 {"/a1/J1_IntArrayDecl2.joos",0},
                 {"/a1/J1_IntCast.joos",0},
                 {"/a1/J1_IntCharInit.joos",0},
                 {"/a1/J1_integerFun1.joos",0},
                 {"/a1/J1_integerFun3.joos",0},
                 {"/a1/J1_integerFun.joos",0},
                 {"/a1/J1_IntInit.joos",0},
                 {"/a1/J1_intliterals.joos",0},
                 {"/a1/J1_intminusfoo.joos",0},
                 {"/a1/J1_IntRange_MinNegativeInt.joos",0},
                 {"/a1/J1_IsThisACast.joos",0},
                 {"/a1/J1_lazybooleanoperations.joos",0},
                 {"/a1/J1_maxint_comment.joos",0},
                 {"/a1/J1_minuschar.joos",0},
                 {"/a1/J1_minusminusminus.joos",0},
                 {"/a1/J1_NamedTypeArray.joos",0},
                 {"/a1/J1_NegativeByteCast.joos",0},
                 {"/a1/J1_NegativeCharCast.joos",0},
                 {"/a1/J1_NegativeIntCast1.joos",0},
                 {"/a1/J1_NegativeIntCast2.joos",0},
                 {"/a1/J1_negativeintcast3.joos",0},
                 {"/a1/J1_NegativeOneByteByteCast.joos",0},
                 {"/a1/J1_NegativeOneByteCharCast.joos",0},
                 {"/a1/J1_NegativeOneByteIntCast.joos",0},
                 {"/a1/J1_NegativeOneByteShortCast.joos",0},
                 {"/a1/J1_NegativeShortCast.joos",0},
                 {"/a1/J1_newobject.joos",0},
                 {"/a1/J1_nonemptyconstructor.joos",0},
                 {"/a1/J1_nullinstanceof1.joos",0},
                 {"/a1/J1_nullliteral.joos",0},
                 {"/a1/J1_octal_escape2.joos",0},
                 {"/a1/J1_octal_escape3.joos",0},
                 {"/a1/J1_octal_escape4.joos",0},
                 {"/a1/J1_octal_escape5.joos",0},
                 {"/a1/J1_octal_escape.joos",0},
                 {"/a1/J1_primitivecasts.joos",0},
                 {"/a1/J1_protectedfields.joos",0},
                 {"/a1/J1_protected.joos",0},
                 {"/a1/J1_publicclasses.joos",0},
                 {"/a1/J1_publicconstructors.joos",0},
                 {"/a1/J1_publicfields.joos",0},
                 {"/a1/J1_publicmethods.joos",0},
                 {"/a1/J1_SimpleTypeArray.joos",0},
                 {"/a1/J1_SmallInt.joos",0},
                 {"/a1/J1_staticmethoddeclaration.joos",0},
                 {"/a1/J1_stringliteralinvoke.joos",0},
                 {"/a1/J1_stringliterals.joos",0},
                 {"/a1/J1_weird_chars.joos",0},
                 {"/a1/J1w_Interface.joos",0},
                 {"/a1/J1w_RestrictedNative.joos",0},
                 {"/a1/J1w_StaticField.joos",0},
                 {"/a1/J2_staticfielddeclaration.joos",0},
                 {"/a1/J2_staticFieldDecl.joos",0},
                 {"/a1/Je_1_AbstractClass_AbstractConstructor.joos",42},
                 {"/a1/Je_1_AbstractClass_Final.joos",42},
                 {"/a1/Je_1_AbstractMethod_Body.joos",42},
                 {"/a1/Je_1_AbstractMethod_EmptyBody.joos",42},
                 {"/a1/Je_1_AbstractMethodCannotBeFinal.joos",42},
                 {"/a1/Je_1_AbstractMethod_Final.joos",42},
                 {"/a1/Je_1_AbstractMethod_Static.joos",42},
                 {"/a1/Je_1_Access_PrivateLocal.joos",42},
                 {"/a1/Je_1_Access_ProtectedLocal.joos",42},
                 {"/a1/Je_1_Access_PublicLocal.joos",42},
                 {"/a1/Je_1_Array_Data_Empty.joos",42},
                 {"/a1/Je_1_Array_Data.joos",42},
                 {"/a1/Je_1_Array_OnVariableNameInDecl.joos",42},
                 {"/a1/Je_1_Cast_LeftHandSideOfAssignment_1.joos",42},
                 {"/a1/Je_1_Cast_LeftHandSideOfAssignment_2.joos",42},
                 {"/a1/Je_1_Methods_NonAbstractNoBody.joos",42},
                 {"/a1/Je_16_IncDec_Final_ArrayLengthDec.joos",42},
                 {"/a1/Je_16_IncDec_Final_ArrayLengthInc.joos",42},
                 {"/a1/Je_16_IncDec_Final_PostDec.joos",42},
                 {"/a1/Je_16_IncDec_Final_PostInc.joos",42},
                 {"/a1/Je_16_IncDec_Final_PreDec.joos",42},
                 {"/a1/Je_16_IncDec_Final_PreInc.joos",42},
                 {"/a1/Je_16_IncDec_StringPostDec.joos",42},
                 {"/a1/Je_16_IncDec_StringPostInc.joos",42},
                 {"/a1/Je_16_IncDec_StringPreDec.joos",42},
                 {"/a1/Je_16_IncDec_StringPreInc.joos",42},
                 {"/a1/Je_16_StaticThis_ArgumentToSuper.joos",42},
                 {"/a1/Je_16_SuperThis_InvalidSuperParameter.joos",42},
                 {"/a1/Je_16_Throw_NoThrows.joos",42},
                 {"/a1/Je_16_Throw_NotSubclass.joos",42},
                 {"/a1/Je_16_Throw_SimpleType.joos",42},
                 {"/a1/Je_16_Throws_This.joos",42},
                 {"/a1/Je_16_Throw_ThrowsNotSuperclass.joos",42},
                 {"/a1/Je_17_Unreachable_AfterThrowInConditional.joos",42},
                 {"/a1/Je_17_Unreachable_AfterThrow.joos",42},
                 {"/a1/Je_1_Escapes_1DigitOctal_1.joos",42},
                 {"/a1/Je_1_Escapes_1DigitOctal_2.joos",42},
                 {"/a1/Je_1_Escapes_1DigitOctal_3.joos",42},
                 {"/a1/Je_1_Escapes_1DigitOctal_4.joos",42},
                 {"/a1/Je_1_Escapes_2DigitOctal_1.joos",42},
                 {"/a1/Je_1_Escapes_2DigitOctal_2.joos",42},
                 {"/a1/Je_1_Escapes_2DigitOctal_3.joos",42},
                 {"/a1/Je_1_Escapes_3DigitOctal_1.joos",42},
                 {"/a1/Je_1_Escapes_3DigitOctal_2.joos",42},
                 {"/a1/Je_1_Escapes_3DigitOctal_3.joos",42},
                 {"/a1/Je_1_Escapes_NonExistingEscape.joos",42},
                 {"/a1/Je_1_Identifiers_Goto.joos",42},
                 {"/a1/Je_1_Identifiers_Private.joos",42},
                 {"/a1/Je_1_IncDec_IncDecNotLvalue.joos",42},
                 {"/a1/Je_1_IncDec_Parenthesized.joos",42},
                 {"/a1/Je_1_IntRange_PlusTooBigInt.joos",42},
                 {"/a1/Je_1_IntRange_TooBigInt_InInitializer.joos",42},
                 {"/a1/Je_1_IntRange_TooBigIntNegated.joos",42},
                 {"/a1/Je_1_JoosTypes_Double.joos",42},
                 {"/a1/Je_1_JoosTypes_Float.joos",42},
                 {"/a1/Je_1_JoosTypes_Long.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_BitwiseXOR.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Bitwise_Negation.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Break.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Choice.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Continue.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_DoWhile.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_PrivateFields.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_PrivateMethods.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Strictftp.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_SuperMethodCall.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Switch.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Synchronized.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_SynchronizedStatement.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Transient.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Unicode.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_Volatile.joos",42},
                 {"/a1/Je_1_SuperThis_SuperAfterBlock.joos",42},
                 {"/a1/Je_1_SuperThis_SuperAfterStatement.joos",42},
                 {"/a1/Je_1_SuperThis_SuperInBlock.joos",42},
                 {"/a1/Je_1_SuperThis_SuperInMethod.joos",42},
                 {"/a1/Je_1_SuperThis_SuperThis.joos",42},
                 {"/a1/Je_1_SuperThis_TwoSuperCalls.joos",42},
                 {"/a1/Je_1_Throw_NotExpression.joos",42},
                 {"/a1/Je_1_Throws_Array.joos",42},
                 {"/a1/Je_1_Throws_SimpleType.joos",42},
                 {"/a1/Je_1_Throws_Void.joos",42},
                 {"/a1/Je_Throws.joos",42},
                 {"/a1/Je_1_ClassInstantiation_InstantiateSimpleType.joos",42},
                 {"/a1/Je_1_ClassInstantiation_InstantiateSimpleValue.joos",42},
                 {"/a1/Je_1_Extends_NamedTypeArray.joos",42},
                 {"/a1/Je_1_Extends_SimpleTypeArray.joos",42},
                 {"/a1/Je_1_Extends_SimpleType.joos",42},
                 {"/a1/Je_1_Extends_Value.joos",42},
                 {"/a1/Je_1_Formals_Final.joos",42},
                 {"/a1/Je_1_Formals_Initializer_Constructor.joos",42},
                 {"/a1/Je_1_Formals_Initializer_Method.joos",42},
                 {"/a1/Je_1_For_NotAStatementInUpdate.joos",42},
                 {"/a1/Je_1_For_PrimaryExpInInit.joos",42},
                 {"/a1/Je_1_For_PrimaryExpInUpdate.joos",42},
                 {"/a1/Je_1_For_StatementInInit.joos",42},
                 {"/a1/Je_1_Implements_NamedTypeArray.joos",42},
                 {"/a1/Je_1_Implements_SimpleTypeArray.joos",42},
                 {"/a1/Je_1_Implements_SimpleType.joos",42},
                 {"/a1/Je_1_Implements_Value.joos",42},
                 {"/a1/Je_1_InstanceInitializers.joos",42},
                 {"/a1/Je_1_InstanceOf_Null.joos",42},
                 {"/a1/Je_1_InstanceOf_Primitive.joos",42},
                 {"/a1/Je_1_InstanceOf_Void.joos",42},
                 {"/a1/Je_1_Interface_ConstructorAbstract.joos",42},
                 {"/a1/Je_1_Interface_ConstructorBody.joos",42},
                 {"/a1/Je_1_IntRange_TooBigInt_InInitializer.joos",42},
                 {"/a1/Je_1_LabeledStatements.joos",42},
                 {"/a1/Je_1_Literals_Class.joos",42},
                 {"/a1/Je_1_Literals_Exponential.joos",42},
                 {"/a1/Je_1_Literals_Float.joos",42},
                 {"/a1/Je_1_Literals_Hex.joos",42},
                 {"/a1/Je_1_Literals_Long.joos",42},
                 {"/a1/Je_1_Literals_Octal.joos",42},
                 {"/a1/Je_1_Locals_Final.joos",42},
                 {"/a1/Je_1_MultiArrayCreation_Assign_2.joos",42},
                 {"/a1/Je_1_MultiArrayCreation_MissingDimension_1.joos",42},
                 {"/a1/Je_1_MultiArrayCreation_MissingDimension_2.joos",42},
                 {"/a1/Je_1_MultiArrayCreation_MissingDimension_4.joos",42},
                 {"/a1/Je_1_MultiArrayCreation_NoType.joos",42},
                 {"/a1/Je_1_MultiArrayTypes_Dimensions.joos",42},
                 {"/a1/Je_1_NegIntTooLow.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_BitwiseAnd.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_BitwiseOr.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_Divide.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_Minus.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_Multiply.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_Plus.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_Remainder.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_ShiftLeft.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_SignShiftRight.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_AssignmentOperations_ZeroShiftRight.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_BitShift_Left.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_BitShift_SignRight.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_BitShift_ZeroRight.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_ExpressionSequence.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_MultipleTypesPrFile.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_NestedTypes.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_StaticInitializers.joos",42},
                 {"/a1/Je_1_NonJoosConstructs_UnaryPlus.joos",42},
                 {"/a1/Je_1_SuperThis_ThisAfterStatement.joos",42},
                 {"/a1/Je_1_SuperThis_ThisInMethod.joos",42},
                 {"/a1/Je_1_VoidType_ArrayCreation.joos",42},
                 {"/a1/Je_1_VoidType_ArrayDeclaration.joos",42},
                 {"/a1/Je_1_VoidType_Cast.joos",42},
                 {"/a1/Je_1_VoidType_Field.joos",42},
                 {"/a1/Je_1_VoidType_Formals.joos",42},
                 {"/a1/Je_1_VoidType_Local.joos",42},
                 {"/a1/Je_1_VoidType_VoidMethod.joos",42},
                 {"/a1/Je_6_Assignable_Instanceof_SimpleTypeOfSimpleType.joos",42},
                 {"/a1/Je_6_InstanceOf_Primitive_1.joos",42},
                 {"/a1/Je_6_InstanceOf_Primitive_2.joos",42},
                 {"/a1/Je_1_Interface_MethodBody.joos",42},
                 {"/a1/Je_1_Interface_NoBody.joos",42},
                 {"/a1/Je_1_For_DeclarationInUpdate.joos",42},
                 {"/a1/Je_1_Methods_StaticFinal.joos",42},
                 {"/a1/Je_Native.joos",42},
                 {"/a1/Je_1_Interface_FinalMethod.joos",42},
                 {"/a1/Je_1_Interface_StaticMethod.joos",42},
                 {"/a1/Je_1_Declarations_MultipleVars_Fields.joos",42},
                 {"/a1/Je_1_Declarations_MultipleVars.joos",42},
                 {"/a1/Je_1_For_MultipleUpdates.joos",42},
                 {"/a1/Je_1_For_MultipleDeclarationsInInit.joos",42},
                 {"/a1/Je_1_Interface_Field.joos",42},
                 {"/a1/Je_16_MultiArrayCreation_Assign_1.joos",42},
                 {"/a1/Je_16_MultiArrayCreation_Null.joos",42},
                 {"/a1/Je_1_Methods_MissingAccessModifier.joos",42},
                 {"/a1/Je_1_PackagePrivate_Class.joos",42},
                 {"/a1/Je_1_PackagePrivate_Field.joos",42},
                 {"/a1/Je_1_PackagePrivate_Method.joos",42},
                 {"/a1/Je_1_FinalField_NoInitializer.joos",42},
                 {"/a1/Je_1_IntRange_MinusTooBigInt.joos",42},
                 {"/a1/Je_16_StaticThis_ArgumentToThis.joos",42},
                 {"/a1/Je_1_ClassDeclaration_WrongFileName_Dot.foo.joos",42},
                 {"/a1/Je_1_ClassDeclaration_WrongFileName.joos",42},
                 {"/a1/Je_1_ClassDeclaration_WrongFileName_Suffix.joos",42},
                 {"/a1/Je_1_Interface_WrongFileName.joos",42},
                 {"/a1/Je_1_IntRange_MinusTooBigInt.joos",42},
                 {"/a1/Je_16_Circularity_1.joos",42},
                 {"/a1/Je_16_Circularity_2.joos",42},
                 {"/a1/Je_16_Circularity_3.joos",42},
                 {"/a1/Je_16_Circularity_4_Rhoshaped.joos",42},
                 {"/a1/Je_16_ClosestMatch_Array.joos",42},
                 {"/a1/Je_16_SuperThis_InvalidThisParameter.joos",42},
                 {"/a1/Je_16_ClosestMatch_Constructor_NoClosestMatch_This.joos",42},
                 {"/a1/Je_1_Cast_DoubleParenthese.joos",42},
                 {"/a1/Je_1_Cast_Expression.joos",42},
                 {"/a1/Je_1_Cast_NonstaticField.joos",42},
                 {"/a1/Je_1_Cast_ToMethodInvoke.joos",42},
                 {"/a1/Je_1_CastToArrayLvalue.joos",42}*/
        };

        return Arrays.asList(A1Tests);
    }

    @Test
    public void runTests(){
        File in = new File(this.getClass().getResource(_inputFile).getFile());
        String [] list = {in.getAbsolutePath()};
        //int returnCode=joosCompiler.compile(list);
        //assertThat(returnCode).isEqualTo(_expectedReturnCode);
    }

    @After
    public void cleanup(){
        CodeCleaner.cleanCode(CodeCleaner.DEFAULT_DIR);
    }
}